# Generated by Django 4.2.3 on 2023-09-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='.static/img/profiles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surnames',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
