# Generated by Django 4.2.3 on 2023-09-13 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0002_profile_location_profile_name_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('n_trades', models.BigIntegerField(default=0)),
                ('promotional_image', models.ImageField(null=True, upload_to='./static/img/communities')),
                ('community_image', models.ImageField(upload_to='./static/img/communities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(upload_to='./static/img/trades')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truequeloop_app.community')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='./static/img/profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surnames',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='TradeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_image', models.ImageField(null=True, upload_to='./static/img/trades')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truequeloop_app.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truequeloop_app.profile'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='truequeloop_app.trade')),
                ('location_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='truequeloop_app.profile')),
            ],
        ),
    ]
