# Generated by Django 4.2.3 on 2023-09-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0003_community_trade_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_trade',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_user',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='truequeloop_app.location'),
        ),
        migrations.AddField(
            model_name='trade',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='truequeloop_app.location'),
        ),
    ]
