# Generated by Django 4.2.3 on 2023-09-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0005_rename_location_user_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeimages',
            name='trade_image',
        ),
        migrations.AddField(
            model_name='tradeimages',
            name='trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truequeloop_app.trade'),
        ),
        migrations.AlterField(
            model_name='tradeimages',
            name='image',
            field=models.ImageField(null=True, upload_to='./static/img/trades'),
        ),
    ]
