# Generated by Django 4.2.3 on 2023-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0007_alter_profile_location_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='surnames',
            field=models.CharField(max_length=120, verbose_name='Apellidos'),
        ),
    ]
