# Generated by Django 4.2.3 on 2023-09-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0008_alter_profile_surnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surnames',
        ),
    ]
