# Generated by Django 4.2.3 on 2023-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0009_remove_profile_name_remove_profile_surnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='promotional_image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/img/communities'),
        ),
    ]
