# Generated by Django 4.2.3 on 2023-09-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0011_trade_interested_trade_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='user_id',
            new_name='user',
        ),
    ]
