# Generated by Django 4.2.3 on 2023-09-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0012_rename_user_id_trade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade',
        ),
    ]
