# Generated by Django 4.2.3 on 2023-10-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truequeloop_app', '0014_trade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenChat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='community',
            name='community_image',
            field=models.ImageField(upload_to='./communities'),
        ),
        migrations.AlterField(
            model_name='community',
            name='promotional_image',
            field=models.ImageField(blank=True, null=True, upload_to='./communities'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/default-user.jpg', null=True, upload_to='./profiles/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='main_image',
            field=models.ImageField(upload_to='./trades/'),
        ),
        migrations.DeleteModel(
            name='OpenChats',
        ),
        migrations.AddField(
            model_name='openchat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='truequeloop_app.message'),
        ),
        migrations.AddField(
            model_name='openchat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_openchats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openchat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_openchats', to=settings.AUTH_USER_MODEL),
        ),
    ]
