# Generated by Django 4.2.3 on 2023-10-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0015_openchat_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openchat',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truequeloop_app.openchat'),
        ),
    ]
