# Generated by Django 4.2.3 on 2023-10-28 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truequeloop_app', '0017_alter_tradeimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_description', models.TextField(max_length=1000)),
                ('sug_image', models.ImageField(blank=True, null=True, upload_to='./communities/')),
                ('approved', models.BooleanField(null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
