# Generated by Django 4.2.3 on 2023-10-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeloop_app', '0019_alter_communityrequest_sug_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='promotional_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
